In [27]:
# numpy相关的统计函数

import numpy as np

arr1 = np.array([[1,2,3,4,5],[6,7,8,9,10]])

arr1

# np.mean()	所有元素的平均值
np.mean(arr1)

# np.sum()	所有元素的和
np.sum(arr1)
# np.max()	所有元素的最大值
np.max(arr1,axis=1)
# np.min()	所有元素的最小值
np.min(arr1,axis=0)
# np.std()	所有元素的标准差

# arr1 = np.arange(5)
# np.std(arr1)
# np.var()	所有元素的方差
# np.var(arr1)

# np.argmax()	最大值的下标索引值
np.argmax(arr1,axis=1)
# np.argmin()	最小值的下标索引值
np.argmin(arr1)
# np.cumsum()	返回一个一维数组，每个元素都是之前所有元素的累加和
np.cumsum(arr1,axis=1)

# np.cumprod()	返回一个一维数组，每个元素都是之前所有元素的累乘积
np.cumprod(arr1)


array([      1,       2,       6,      24,     120,     720,    5040,
         40320,  362880, 3628800])

In [34]:
# 比较函数
# np.any()	至少有一个元素满足指定条件，就返回True
# np.all()	所有的元素都满足指定条件，才返回True

arr2 = np.array([[1,2,3],[4,5,6]])
arr2
np.any(arr2 > 3)
np.all(arr2 > 3)

np.False_

In [56]:
# 排序函数
arr3 = np.array([[3,6,4],[2,7,5],[9,8,1]])
# ndarry.sort()  是对数组对象进行原地排序   不会创建新的对象
arr3.sort(axis=0)
arr3

# np.sort() 返回的是排好序的新数组对象
# np.sort(arr3,axis=0)


array([[2, 6, 1],
       [3, 7, 4],
       [9, 8, 5]])

In [53]:
# 去重函数
arr1 = np.random.randint(0, 5, (3, 3))
print(arr1)
print(np.unique(arr1))


[[2 2 3]
 [1 1 1]
 [0 2 4]]
[0 1 2 3 4]
