In [1]:
# array 和asarray
# array()：将输入数据转换为ndarray，会进行copy。
# asarray()：将输入数据转换为ndarray，如果输入本身是ndarray则不会进行copy。

import numpy as np
data = [1,2,3]
print(f"data的内存地址->{id(data)}")

# 如果传递的参数是一个list，array和asarray没有什么区别，都是将列表封装为一个新的数组对象
arr1 = np.array(data)
print(arr1)
print(type(arr1))
print(f"arr1的内存地址->{id(arr1)}")

# arr1 = np.asarray(data)
# print(arr1)
# print(type(arr1))
# print(f"arr1的内存地址->{id(arr1)}")
print("~~~~~~~~~~~~~~")
# 如果传递的参数是数组，array会进行copy，创建一个新的对象
arr2 = np.array(arr1)
print(arr2)
print(type(arr2))
print(f"arr2的内存地址->{id(arr2)}")

print("~~~~~~~~~~~~~~")
# 如果传递的参数是数组，asarray不会进行copy，和参数数组指向同一个对象
arr3 = np.asarray(arr1)
print(arr3)
print(type(arr3))
print(f"arr3的内存地址->{id(arr3)}")



data的内存地址->4552237312
[1 2 3]
<class 'numpy.ndarray'>
arr1的内存地址->4558027920
~~~~~~~~~~~~~~
[1 2 3]
<class 'numpy.ndarray'>
arr2的内存地址->4562345328
~~~~~~~~~~~~~~
[1 2 3]
<class 'numpy.ndarray'>
arr3的内存地址->4558027920


In [22]:
# zeros()：返回给定形状和类型的新数组，用0填充。
arr = np.zeros((2,3))
# ones()：返回给定形状和类型的新数组，用1填充。
# arr = np.ones((2,3))
# arr
# arr.dtype
# empty()：返回给定形状和类型的未初始化的新数组。
# arr = np.empty((5,8))
# arr

# zeros_like()：返回与给定数组具有相同形状和类型的0新数组。
# np.zeros_like(arr)
# ones_like()：返回与给定数组具有相同形状和类型的1新数组。
# np.ones_like(arr)
# empty_like()：返回与给定数组具有相同形状和类型的未初始化的新数组
np.empty_like(arr)




array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
# full()：返回给定形状和类型的新数组，用指定的值填充。
# full_like()：返回与给定数组具有相同形状和类型的用指定值填充的新数组。
arr = np.full((2,3),6)
np.full_like(arr,8)


array([[8, 8, 8],
       [8, 8, 8]])

In [28]:
# arange()：返回在给定范围内用均匀间隔的值填充的一维数组。
arr = np.arange(0,10,2)
print(type(arr))

<class 'numpy.ndarray'>


In [33]:
# linspace()：返回指定范围和元素个数的等差数列。数组元素类型为浮点型。
# np.linspace(0,10,5,endpoint=True)
np.linspace(0,10,5,endpoint=False)
# logspace()：返回指定指数范围、元素个数、底数的等比数列。
np.logspace(start=2,stop=5,num=4,base=2)


array([ 4.,  8., 16., 32.])

In [45]:
# random.rand()：返回给定形状的数组，用 [0, 1) 上均匀分布的随机样本填充。
np.random.rand(2,3)
# random.randint()：返回给定形状的数组，用从低位(包含)到高位(不包含)上均匀分布的随机整数填充。
np.random.randint(low=0,high=5,size=(2,3))
# random.uniform()：返回给定形状的数组，用从低位(包含)到高位(不包含)上均匀分布的随机浮点数填充。
np.random.uniform(low=0,high=5,size=(2,3))
# random.randn()：返回给定形状的数组，用标准正态分布(均值为0，标准差为1)的随机样本填充。
np.random.randn(2,3)


array([[-1.99625256,  1.35269598,  0.59324126],
       [ 1.17759512,  0.95990391,  1.42555313]])

In [48]:
aa = np.matrix("1,2;3,4")
print(type(aa))
np.matrix([[1, 2], [3, 4]])

<class 'numpy.matrix'>


matrix([[1, 2],
        [3, 4]])